### ISSUE TITLE
Attributes in tutorial don't match?

### ISSUE THREAD

**Issue by christine-liu** [raquelgarza/truster#12]
Hi!
I'm trying to use trusTEr to analyze some single-cell samples I have already analyzed in cellranger and Seurat.
I'm starting with the steps to create an Experiment and register the samples, using the following commands:
`project=truster.Experiment(name="test_project")`
`project.register_sample(sample_id="Sample1", sample_name="Sample1")`
but I keep getting an error
`AttributeError: 'Experiment' object has no attribute 'register_sample'`

Using `dir(project)` it looks like the attribute is actually `registerSample` and not `register_sample` as listed in the tutorial. I installed trusTEr using pip and believe it's version 0.1.1 -- is this not up to date?

Thanks for your help!
Christine

**Comment by raquelgarza** [comment]
Hi Christine,

Thank you for the interest! Indeed, what you are seeing is an old version of the documentation. Where did you access it? Can't seem to find any of the link in the github with this nomenclature.

In anyway, you here is a workflow example that is up to date: https://raquelgarza.github.io/truster/post/migrate-from-jekyll/

Let me know if you still encounter this issue

**Comment by christine-liu** [comment]
Hi Raquel,

I just followed the link at the bottom (https://raquelgarza.github.io/truster) so I'm not sure how that got me to an older version -- I can see the up-to-date version now! 

Thanks!
